please review autocomplete search
v1lya/WeathUp pull request #5
Opened 2021-04-23 19:42 UTC by v1lya

implemented autocomplete search

2021-04-23 21:17 UTC, v1lya commented
Please use value 'tel' for autocomplete search and choose cities Tel Aviv or Telavi there.

2021-04-25 07:31 UTC, borisovmi requested changes

2021-04-25 07:31 UTC, borisovmi commented on src/styles.css
> +  background: url('src/assets/background/day.svg') no-repeat fixed;
i think you can use url without "src"

2021-04-25 07:31 UTC, borisovmi commented on src/app/app.module.ts
> +        MaterialModule
indentation

2021-04-25 07:31 UTC, borisovmi commented on src/app/core/city-weather/search/search-field/search-field.component.ts
> +            return this.httpService.getAutocompleteSearchResults(value.toLowerCase().replace(/[\s]/g, ''));
it's better to make value transformations (.toLowerCase, .replace) as a separate stage. 
it makes code more readable and simple. also, if one day you will add tests, it will be easier to write tests when you have code splitted to smaller parts.
either add map operator before switchMap, or move this already to httpService.getAutocompleteSearchResults

2021-04-25 07:31 UTC, borisovmi commented on src/app/core/city-weather/search/search-result/search-result.component.ts
> +      this.router.navigate(['/']);
looks like logic which can be put in a guard

2021-04-25 07:31 UTC, borisovmi commented on src/app/core/city-weather/search/search-result/search-result.component.ts
>        this.httpService.getCityWeather(this.defaultCityName)
this.httpService.getCityWeather(this.defaultCityName) and this.getFavoriteCityWeather() can be merged with merge operator because they have a similar logic inside subscription

2021-04-25 13:43 UTC, v1lya commented on src/app/app.module.ts
> +        MaterialModule
done

2021-04-25 13:45 UTC, v1lya commented on src/styles.css
> +  background: url('src/assets/background/day.svg') no-repeat fixed;
done

2021-04-25 14:04 UTC, v1lya commented on src/app/core/city-weather/search/search-field/search-field.component.ts
> +            return this.httpService.getAutocompleteSearchResults(value.toLowerCase().replace(/[\s]/g, ''));
thank you! done.

2021-04-25 14:51 UTC, v1lya commented on src/app/core/city-weather/search/search-result/search-result.component.ts
>        this.httpService.getCityWeather(this.defaultCityName)
done

2021-04-25 15:48 UTC, v1lya commented on src/app/core/city-weather/search/search-result/search-result.component.ts
> +      this.router.navigate(['/']);
done

2021-04-26 05:37 UTC, borisovmi commented on src/app/favorites-list/favorite-item/favorite-city.guard.ts
> +      this.router.navigate(['/']);
you need to `return false` after the navigate method.

2021-04-26 05:37 UTC, borisovmi commented on src/app/favorites-list/favorite-item/favorite-city.guard.ts
> +  canActivate(route: ActivatedRouteSnapshot, state: RouterStateSnapshot): Observable<boolean | UrlTree> | Promise<boolean | UrlTree> | boolean | UrlTree {
leave only relevant return type for canActivate

2021-04-26 07:28 UTC, v1lya commented on src/app/favorites-list/favorite-item/favorite-city.guard.ts
> +      this.router.navigate(['/']);
done

2021-04-26 07:29 UTC, v1lya commented on src/app/favorites-list/favorite-item/favorite-city.guard.ts
> +  canActivate(route: ActivatedRouteSnapshot, state: RouterStateSnapshot): Observable<boolean | UrlTree> | Promise<boolean | UrlTree> | boolean | UrlTree {
done

2021-04-26 08:06 UTC, borisovmi approved these changes

2021-04-26 08:41 UTC, merged